Updating pre-commit hook

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -1,34 +1,13 @@
 #!/bin/bash
 
-echo "Running Ktlint before git commit."
+echo "Running ktlintCheck pre-commit hook"
 
-./gradlew ktlintFormat
+./gradlew KtlintCheck
 
-RESULT=$?
+STATUS=$?
 
-git stash pop -q
+# return exit code 1 if running check fails
+[ $STATUS -ne 0 ] && exit 1
+exit 0
 
-# return 1 exit code if running checks fails
-[ $RESULT -ne 0 ] && exit 1
-
-######## KTLINT-GRADLE HOOK START ########
-
-CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.kts|\.kt/ { print $2}')"
-
-if [ -z "$CHANGED_FILES" ]; then
-    echo "No Kotlin staged files."
-    exit 0
-fi;
-
-echo "Running ktlint over these files:"
-echo "$CHANGED_FILES"
-
-./gradlew --quiet ktlintFormat -PinternalKtlintGitFilter="$CHANGED_FILES"
-
-echo "Completed ktlint run."
-echo "$CHANGED_FILES" | while read -r file; do
-    if [ -f $file ]; then
-        git add $file
-    fi
-done
-echo "Completed ktlint hook."
+echo "Completed ktlintCheck pre-commit hook."
